### ISSUE TITLE
Downloads: not clear how to choose between 2.12 and 2.11

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-streampark-website#356]
https://github.com/apache/incubator-streampark-website/blob/d18115a4f6ea0a04080d5fc48b40fa8ce067fbdd/src/pages/download/languages.json#L27

There are two similar looking artifacts on the download page [1]

apache-streampark_2.12-2.1.3-incubating-bin.tar.gz
apache-streampark_2.11-2.1.3-incubating-bin.tar.gz

What is the difference between them? How is one supposed to choose?
It would be useful to have an explanation of what these are for.

[1] https://streampark.apache.org/download

**Comment by wolfboys** [comment]
> It would help to explain this on the download page.

Thanks for your reminder, I will submit a PR to solve this issue.

**Comment by wolfboys** [comment]
Thanks again for your feedback, the download page has been updated: https://github.com/apache/incubator-streampark-website/pull/365
