### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-streampark-website#369]
https://github.com/apache/incubator-streampark-website/blob/40457551aac27c0684f87e39d0a4fb4c8f4e9669/docusaurus.config.js#L245

The /en and /zh-CN links don't work

**Comment by tisonkun** [comment]
This should be fixed now. See the commit message for more details.

However, loading the homepage has a obvious lag (about 1-2 seconds), perhaps @wolfboys @harae can take a look.
